server:
  port: 8989
  context-path: /manager
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/struggle?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml


